# Lineare Regression mit mehreren Variablen

In [22]:
import pandas as pd #import pandas libary (working with csv file)

csvdata = pd.read_csv("./hotels.csv")   # pd.read_excel("filename.xlsx") // pd.read_csv("filename.csv", sep=";")

In [23]:
csvdata.head()

Gewinn  Preis in Mio  Quadratmeter    Stadt
0  119000.0         21.88        3938.0   Berlin
1  250000.0         27.95        3986.0  München
2  250000.0         16.09        2574.0     Köln
3  145000.0         27.58        4155.0  München
4  110000.0         23.76        3795.0   Berlin

In [24]:
X = csvdata[["Gewinn", "Quadratmeter"]].values  # safe only values (without header = second [])
Y = csvdata[["Preis in Mio"]].values    # numpy array

In [25]:
from sklearn.model_selection import train_test_split    # libary -> zum daten aufsplitten

# audfteilung der werte X,Y auf deklaration //  random_state = rnd aufteilen // test_size = prozentualer anteil für test daten
X_train, X_test, y_train, y_test = train_test_split(X, Y, random_state = 0, test_size = 0.25)

In [26]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [27]:
print(model.intercept_)

[6.48370247]


In [28]:
print(model.coef_)

[[6.39855984e-06 3.89642288e-03]]


In [29]:
# 6.48370247 + [Gewinn] * 6.39855984e-06 + [Quadrameter] * 3.89642288e-03

In [30]:
y_test_pred = model.predict(X_test)


In [31]:
 y_test_pred     # = vorausgesagten werte

array([[15.48428777],
       [19.25848937],
       [13.05937756],
       [25.49068515],
       [ 6.81600627],
       [21.62782213],
       [13.89794657],
       [11.48552582],
       [13.36299543],
       [30.30074569],
       [14.54450876],
       [24.78636769],
       [22.51853591],
       [17.36475207],
       [14.6587811 ],
       [ 9.37005463],
       [21.41982044],
       [ 6.94709036],
       [11.35222603],
       [17.65669735],
       [29.27103676],
       [ 7.17558502],
       [21.88603479],
       [21.65328149],
       [19.90957541],
       [16.73928148],
       [27.34973807],
       [28.53818494],
       [13.89007794],
       [12.50191932],
       [10.68589983],
       [ 9.42238885],
       [10.12896444],
       [ 9.83562033],
       [15.90798701],
       [13.00094789],
       [17.32972215],
       [18.35066072]])

In [32]:
 y_test    #   = echten werte

array([[14.56],
       [16.32],
       [13.09],
       [22.87],
       [ 8.94],
       [19.13],
       [13.77],
       [ 9.63],
       [10.41],
       [32.78],
       [12.98],
       [23.6 ],
       [20.27],
       [21.26],
       [13.86],
       [ 9.76],
       [24.81],
       [ 6.62],
       [ 8.69],
       [14.16],
       [28.49],
       [ 6.95],
       [22.4 ],
       [24.87],
       [16.94],
       [15.54],
       [24.78],
       [30.14],
       [16.15],
       [17.75],
       [ 7.91],
       [ 7.98],
       [ 6.73],
       [ 6.3 ],
       [13.21],
       [10.94],
       [19.59],
       [15.18]])

In [33]:
for i in range(0, len(y_test_pred)):    # von 0 bis anzahl der elemente in den test daten
    print(str(y_test_pred[i][0]) + " - " + str(y_test[i][0]))

15.484287770456307 - 14.56
19.25848936697959 - 16.32
13.059377556544964 - 13.09
25.490685154062852 - 22.87
6.8160062670562525 - 8.94
21.627822128095936 - 19.13
13.89794656549663 - 13.77
11.48552582135802 - 9.63
13.362995432755909 - 10.41
30.300745693396017 - 32.78
14.544508758730883 - 12.98
24.786367694531798 - 23.6
22.5185359125309 - 20.27
17.364752070043462 - 21.26
14.658781101070202 - 13.86
9.370054632254531 - 9.76
21.419820437400865 - 24.81
6.947090359060695 - 6.62
11.352226027295266 - 8.69
17.656697351169136 - 14.16
29.271036764081238 - 28.49
7.1755850230725 - 6.95
21.886034785667135 - 22.4
21.653281486765614 - 24.87
19.90957541499908 - 16.94
16.739281476364937 - 15.54
27.349738072086637 - 24.78
28.538184939132954 - 30.14
13.890077942623035 - 16.15
12.501919323322051 - 17.75
10.685899826208408 - 7.91
9.422388850520344 - 7.98
10.128964442111489 - 6.73
9.835620333614967 - 6.3
15.90798700549315 - 13.21
13.00094788689616 - 10.94
17.329722152677313 - 19.59
18.350660724427478 - 15.18
