## Numpy kann auch Matritzen!

In [1]:
import numpy as np

np.array([[1, 2, 3], [4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
m = np.array([[1, 2, 3], [4, 5, 6]])

print(m.shape)

(2, 3)


In [10]:
np.ones((2, 3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [11]:
np.zeros((2, 3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [14]:
np.arange(1, 7).reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [15]:
m = np.array([[1, 2, 3], [4, 5, 6]])

print(m)

[[1 2 3]
 [4 5 6]]


In [20]:
m.reshape(6)

array([1, 2, 3, 4, 5, 6])

In [22]:
np.arange(1, 7).reshape(2, -1)

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
np.arange(1, 7).reshape(-1, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [28]:
m = np.array([[1, 2, 3], [4, 5, 6]])

print(m.reshape(-1))

[1 2 3 4 5 6]


In [33]:
np.mean?