## Numpy kann auch Matritzen!

In [2]:
import numpy as np

np.array([[1, 2, 3], [4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
m = np.array([[1, 2, 3], [4, 5, 6]])    # matrix speichern

print(m.shape)          # matrix format ausgeben

(2, 3)


In [4]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [5]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

#### Reshape

In [8]:
np.arange(1, 7).reshape(3, 2)   # 3 zeilen mit jeweils 2 einträgen

array([[1, 2],
       [3, 4],
       [5, 6]])

In [9]:
m = np.array([[1, 2, 3], [4, 5, 6]])

print(m)

[[1 2 3]
 [4 5 6]]


In [10]:
m.reshape(6)

array([1, 2, 3, 4, 5, 6])

In [11]:
np.arange(1, 7).reshape(2, -1)  # -1 berechne automatisch

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
np.arange(1, 7).reshape(-1, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [13]:
m = np.array([[1, 2, 3], [4, 5, 6]])

print(m.reshape(-1))

[1 2 3 4 5 6]


In [14]:
np.mean?